# CONFIGURATION FILE 
# All paths are to be given without final slash.

# Path 
pathFlow: '/Users/joaoisler/Google Drive/My Drive/bsc/scramjet/afrl/2d/cases/euler/case'
pathRes: '/Users/joaoisler/Google Drive/My Drive/bsc/pinns/PINNs/results' 
pathData: '/Users/joaoisler/Google Drive/My Drive/bsc/pinns/PINNs/data' 
 
# Flow field file
flowfield: 'flow.vtu' 

# Routines
routine:
  sampling: True
  inference: False
  identification: False
  training: False
  pinns: False
  gnn: False

# Sampling parameters
sampling:
  nspoin: 6000
  nspoin_extra: 2000 # grad
  Type: 'lhs' # random, lhs
  GradTypeVar: 'Density'
  pool_factor: 8
  alpha_grad_rho: 1.5
  seed: 1234
  graphfilename: 'sampling_graph'
  datafilename: 'sampling_data'

# PINNs steup
N_train: 600
layers: [2, 64, 64, 64, 64, 64, 4]

# General parameters
dims: 2

# Heat capacity ratio 
gamma: 1.4
# Reference quatities
H: 0.0508
Lref: 0.0254 # m
# Freestream condition
U_0: 727.0 # m/s
T: 327.0   # K
p: 61700   # Pa
rho: 0.657 # kg/m^3
# Turbulence modeling
k: 7884.91         # m^2/s^2
omega: 2.62957e+07 # 1/s